export const FETCH_DIVISIONS_LIST_SUCCESS = 'FETCH_DIVISIONS_LIST_SUCCESS';
export const UPDATE_CHECKBOX_CONDITIONS = 'UPDATE_CHECKBOX_CONDITIONS';
export const FETCH_GAME_LIST_SUCCESS = 'FETCH_GAME_LIST_SUCCESS';
